### ISSUE TITLE
Problema com CEP sem bairro

### ISSUE THREAD

**Issue by vitorfba** [Corviz/brasilapi-php#1]
O DTO CepData recebe o parametro $neighborhood como obrigatório, porém alguns ceps do brasil são genéricos e não possuem bairro, ocasionando uma exception.

Por exemplo, o cep: 45150-000

**Comment by carloscarucce** [comment]
Obrigado pelo seu report!

Identifiquei que no mesmo objeto, em alguns casos, outros atributos também não estavam presentes e já coloquei como opcional.

A correção ja está presente na release 1.1.1
